# Use this template to create your own custom action for eunomia
# It should be named eunomia_name_of_function

def lambda_handler(event, context):
    core = EunomiaCore(event)

    # get_step returns the input data for this step in the batch
    step = core.get_step()

    # manually craft your outputs using set_output_kv
    core.set_output_kv("custom_output","This was generated by the function")

    # alternatively use the parse_output function to parse the data using user defined output_format
    try:
        core.parse_output("text or json output from the downstream service that will be parsed")
    except:
        raise

    return core.get_event()
