# Use this template to create your own custom action for eunomia
# It should be named eunomia_name_of_function
import datetime

def lambda_handler(event, context):
    return_object = { "begin_step": str(datetime.datetime.utcnow()) }
    step = event["current_step"]["step"]

    # data for this step will be found in:
    # event["input"][step]

    for key in event["input"][step]:
        return_object[key] = event["input"][step][key]
    
    # add any relevant outputs to return_object
    return_object["custom_output"] = "This was generated by the function"

    return_object["end_step"]= str(datetime.datetime.utcnow())
    event["output"][step] = return_object
    return event
